# Generated by Django 5.2.14 on 2026-05-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('duration', models.IntegerField()),
                ('fees', models.FloatField()),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('course', models.ManyToManyField(to='management.course')),
            ],
        ),
    ]
